Fix pagination issue
beyondcomputing-org/Atlassian.Bitbucket pull request #11
Opened 2021-04-30 00:38 UTC by Ephesoft-Stitus

# Why
Bitbucket has known bug [BCLOUD-20796](https://jira.atlassian.com/browse/BCLOUD-20796) where pagination is broken for the /repositories/{workspace}/{repo_slug}/deployments/ endpoint.  

# What
Added some logic so that if a known bad hostname is returned in the 'next' property, it is replaced and the original endpoint is used with an incremented page number.  This is done because the entire URL returned for pagination is incorrect and cannot be used.  

# Testing
Tested locally with a 78 page response and verified success.

2021-05-03 04:37 UTC, eelkram requested changes

2021-05-03 04:37 UTC, eelkram commented on Atlassian.Bitbucket.Authentication.psm1
> +            $_endpoint = "$($baseUrl)?$(($_endpoint.split('?'))[1])"
1. baseURL has a different casing.
2. For the query string it should have 1-n as it is possible to have a question mark in the query string....
3. I would recommend moving the endpoint construction logic down into the if statement below.  You don't need to post process the first message and it makes it more clear I think what is going on and why.

2021-05-03 04:37 UTC, eelkram commented on Atlassian.Bitbucket.Authentication.psm1
> +            If ($baseURL -match '.*\/repositories\/.*\/.*\/deployments\/') {
I would recommend something like:
`2\.0\/repositories\/[^\/]*\/[^\/]*\/deployments\/$`

It's more specific so we don't get an accidental false positive and it's faster, 35 vs 196 steps.

2021-05-03 14:46 UTC, Ephesoft-Stitus commented on Atlassian.Bitbucket.Authentication.psm1
> +            $_endpoint = "$($baseUrl)?$(($_endpoint.split('?'))[1])"
Yeah, that all makes sense.  I can't put the query string construction in the if statement because we need it every time to avoid future endpoint issues.  However, I can make it much easier to follow.

2021-05-03 15:22 UTC, Ephesoft-Stitus commented on Atlassian.Bitbucket.Authentication.psm1
> +            If ($baseURL -match '.*\/repositories\/.*\/.*\/deployments\/') {
Updated.

2021-05-04 19:00 UTC, eelkram approved these changes
Looks good

2021-05-04 19:03 UTC, merged