branch_type is only valid when branch_match_kind is branching_model
beyondcomputing-org/Atlassian.Bitbucket pull request #18
Opened 2021-08-30 15:01 UTC by variableresistor

Fixed issue running Add-BitbucketRepositoryBranchRestriction that caused error branch_type is only valid when branch_match_kind is branching_model

2021-08-30 15:06 UTC, variableresistor commented
I can't figure out exactly how to run the Pester tests. Just running them from the test file itself doesn't work, I tried checking the contribution guidelines, and finally, I tried checking to see what the build pipeline is doing. But the script it's using is obfuscated and I can't see the script content to replicate it.

2021-09-01 00:46 UTC, eelkram commented
@variableresistor let me see if I can shed some light onto how it works.  The tests are run from [Build.ps1](https://github.com/beyondcomputing-org/Atlassian.Bitbucket/blob/master/Build.ps1).  However, regarding testing it really only installs version 4.10.1 of Pester and then runs the tests.  The rest of the code in that script is all about generating a clean folder for publishing.  It should probably be split apart and cleaned up.

If I were to guess I would assume you probably have the latest version of Pester installed which would cause the issue.  I haven't had a need or time to refactor the tests to run on Pester 5.

Let me know if that helps or if you still have issues.

2021-09-02 05:49 UTC, eelkram requested changes
Changes look good, just need to version bump to 0.29.1 and then i'll merge.

2021-09-02 05:49 UTC, eelkram commented on CHANGELOG.md
> +- Fixed issue running `Add-BitbucketRepositoryBranchRestriction` that caused error `branch_type is only valid when branch_match_kind is branching_model
For the module to be published you will need to bump the version to 0.29.1 (bugfix).  Please update the version in the .psd1 file and then create a new entry in the CHANGELOG.md for 0.29.1.

2021-09-03 19:28 UTC, eelkram approved these changes

2021-09-03 19:28 UTC, merged