Added allow_auto_merge_when_builds_pass
beyondcomputing-org/Atlassian.Bitbucket pull request #22
Opened 2021-10-26 21:34 UTC by variableresistor

Atlassian added a new option to auto-merge when all other merge conditions are fulfilled.

2021-11-01 05:04 UTC, eelkram requested changes
Thanks for the update, just need to version bump the .psd1 file as well so the module can publish.

2021-11-01 17:36 UTC, variableresistor commented on CHANGELOG.md
> +## 0.32.0
@eelkram the version bump here isn't correct?

2021-11-02 00:20 UTC, eelkram commented on CHANGELOG.md
> +## 0.32.0
This is fine, but you also have to bump the version in the .psd1 file as that is what is used to publish the module to the PSGallery.

2021-11-02 00:22 UTC, eelkram commented on CHANGELOG.md
> +## 0.32.0
I think you skipped past step 1 in https://github.com/beyondcomputing-org/Atlassian.Bitbucket/blob/master/CONTRIBUTING.md

2021-11-02 00:23 UTC, eelkram commented on CHANGELOG.md
> +## 0.32.0
You need to make the same version change here: https://github.com/beyondcomputing-org/Atlassian.Bitbucket/blob/master/Atlassian.Bitbucket.psd1#L15

2021-11-02 14:20 UTC, variableresistor commented on CHANGELOG.md
> +## 0.32.0
Oops... I knew that. :-)

2021-11-04 22:00 UTC, eelkram approved these changes
Thanks, looks good.

2021-11-04 22:00 UTC, merged