Add new functions to manage user groups
beyondcomputing-org/Atlassian.Bitbucket pull request #9
Opened 2021-03-10 17:10 UTC by markphelan

2021-03-11 00:42 UTC, eelkram requested changes
Thanks for submitting the PR.  I have a few small comments if you can take a look.  I assume you have tested this locally and confirmed it works as expected.

2021-03-11 00:42 UTC, eelkram commented on Atlassian.Bitbucket.psd1
> +    ModuleVersion     = '0.25.2'
This would be considered a minor bump as it adds new functionality so 0.26.0

2021-03-11 00:42 UTC, eelkram commented on Atlassian.Bitbucket.psd1
> +        'Get-BitbucketUserGroup',
Should we call this Get-BitbucketGroup?

2021-03-11 00:42 UTC, eelkram commented on Atlassian.Bitbucket.Repository.BranchRestriction.psm1
> +    [OutputType([MergeCheck])]
Should the output type just be BranchRestriction?

2021-03-11 00:43 UTC, eelkram commented
Also, please add a changelog entry.

2021-03-11 07:55 UTC, markphelan commented on Atlassian.Bitbucket.psd1
> +        'Get-BitbucketUserGroup',
I was unsure about this as I wrote it to align with "User" functionality and match the label in the web UI, but happy to match the API endpoint path instead and refer to it as Group.

2021-03-11 07:56 UTC, markphelan commented on Atlassian.Bitbucket.Repository.BranchRestriction.psm1
> +    [OutputType([MergeCheck])]
This fails running the Pester checks for me if the OutputType is omitted or does not include MergeCheck:
```
Context Atlassian.Bitbucket.Repository.BranchRestriction.psm1
      [-] On line: 181 - The cmdlet 'ConvertTo-BranchRestriction' returns an object of type 'MergeCheck' but this type is not declared in the OutputType attribute. 23ms
        Expected $false, but got $true.
        25:                                     $true | Should Be $False
        at <ScriptBlock>, C:\Users\mark.phelan\repos\Atlassian.Bitbucket\Tests\1.ScriptAnalyzer.Tests\1.ScriptAnalyzer.Tests.ps1: line 25
```

2021-03-11 07:58 UTC, markphelan commented
> I assume you have tested this locally and confirmed it works as expected.

Yes, used the new functionality to add a user to a group within a workspace I manage.

2021-03-12 04:33 UTC, eelkram approved these changes
Looks good, thanks for the updates!

2021-03-12 04:34 UTC, merged